import 'dotenv/config';
import cors from 'cors';
import express from 'express';
import { createServer } from 'node:http';
import crypto from 'node:crypto';
import { Pool } from 'pg';
import { Server } from 'socket.io';
import { z } from 'zod';
import type { QueueItem, Room, Video } from '@encore/types';

const app = express(); const httpServer = createServer(app); const io = new Server(httpServer,{cors:{origin:process.env.CLIENT_ORIGIN?.split(',')||'*'}});
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
app.use(cors({origin:process.env.CLIENT_ORIGIN?.split(',')||true})); app.use(express.json());
const itemSchema=z.object({youtubeId:z.string().min(1).max(32),title:z.string().min(1).max(255),channelTitle:z.string().min(1).max(255),thumbnailUrl:z.string().url(),duration:z.string().optional(),addedBy:z.string().min(1).max(50)});
const roomCode=()=>crypto.randomBytes(3).toString('hex').toUpperCase().slice(0,4);
async function loadRoom(code:string, includeToken=false):Promise<Room|null>{const r=await pool.query('SELECT * FROM rooms WHERE code=$1',[code]);if(!r.rowCount)return null;const room=r.rows[0];const q=await pool.query('SELECT * FROM queue_items WHERE room_id=$1 AND played_at IS NULL ORDER BY position',[room.id]);const current=await pool.query('SELECT * FROM queue_items WHERE room_id=$1 AND played_at IS NOT NULL ORDER BY played_at DESC LIMIT 1',[room.id]);const map=(x:any):QueueItem=>({id:x.id,youtubeId:x.youtube_id,title:x.title,channelTitle:x.channel_title,thumbnailUrl:x.thumbnail_url,duration:x.duration,addedBy:x.added_by,position:x.position,addedAt:x.created_at});return {code:room.code,name:room.name,...(includeToken?{hostToken:room.host_token}:{}),currentItem:current.rowCount?map(current.rows[0]):null,queue:q.rows.map(map)} }
async function broadcast(code:string){const room=await loadRoom(code);if(room)io.to(code).emit('room:updated',room)}
async function hostAllowed(code:string, token:string|undefined){const r=await pool.query('SELECT 1 FROM rooms WHERE code=$1 AND host_token=$2',[code,token]);return Boolean(r.rowCount)}
app.get('/health',(_req,res)=>res.json({ok:true}));
app.post('/api/rooms',async(req,res)=>{const parsed=z.object({name:z.string().min(1).max(100)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid room name'});for(let i=0;i<4;i++){const code=roomCode();try{await pool.query('INSERT INTO rooms(code,name) VALUES($1,$2)',[code,parsed.data.name]);const room=await loadRoom(code,true);return res.status(201).json(room)}catch(e:any){if(e.code!=='23505')throw e}}res.status(503).json({error:'Could not create room'})});
app.get('/api/rooms/:code',async(req,res)=>{const room=await loadRoom(req.params.code.toUpperCase());room?res.json(room):res.status(404).json({error:'Room not found'})});
app.post('/api/rooms/:code/queue',async(req,res)=>{const parsed=itemSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid video'});const code=req.params.code.toUpperCase();const r=await pool.query('SELECT id FROM rooms WHERE code=$1',[code]);if(!r.rowCount)return res.status(404).json({error:'Room not found'});const position=(await pool.query('SELECT COALESCE(MAX(position),0)+1 AS p FROM queue_items WHERE room_id=$1 AND played_at IS NULL',[r.rows[0].id])).rows[0].p;const v=parsed.data;await pool.query('INSERT INTO queue_items(room_id,youtube_id,title,channel_title,thumbnail_url,duration,added_by,position) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[r.rows[0].id,v.youtubeId,v.title,v.channelTitle,v.thumbnailUrl,v.duration||null,v.addedBy,position]);await broadcast(code);res.status(201).json({ok:true})});
app.post('/api/rooms/:code/skip',async(req,res)=>{const code=req.params.code.toUpperCase();if(!await hostAllowed(code,req.header('x-host-token')||undefined))return res.status(403).json({error:'Host permission required'});const r=await pool.query(`WITH item AS (SELECT qi.id FROM queue_items qi JOIN rooms r ON r.id=qi.room_id WHERE r.code=$1 AND qi.played_at IS NULL ORDER BY qi.position LIMIT 1) UPDATE queue_items SET played_at=now() WHERE id IN (SELECT id FROM item) RETURNING id`,[code]);if(!r.rowCount)return res.status(409).json({error:'Queue is empty'});await broadcast(code);res.json({ok:true})});
app.get('/api/videos/search',async(req,res)=>{const q=z.string().min(2).max(100).safeParse(req.query.q);if(!q.success)return res.status(400).json({error:'Search query must be at least 2 characters'});if(!process.env.YOUTUBE_API_KEY)return res.status(503).json({error:'YouTube search is not configured'});const url=new URL('https://www.googleapis.com/youtube/v3/search');url.search=new URLSearchParams({part:'snippet',type:'video',videoEmbeddable:'true',maxResults:'12',q:`${q.data} karaoke`,key:process.env.YOUTUBE_API_KEY}).toString();const response=await fetch(url);if(!response.ok)return res.status(502).json({error:'YouTube search failed'});const data:any=await response.json();const items:Video[]=data.items.map((x:any)=>({youtubeId:x.id.videoId,title:x.snippet.title,channelTitle:x.snippet.channelTitle,thumbnailUrl:x.snippet.thumbnails.medium?.url||x.snippet.thumbnails.default.url}));res.json({items})});
io.on('connection',socket=>socket.on('room:join',(code:string)=>socket.join(code.toUpperCase())));
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);if(err?.code==='42P01')return res.status(503).json({error:'Database schema is missing. Apply apps/api/src/db/schema.sql, then retry.'});if(['ECONNREFUSED','ENOTFOUND','3D000'].includes(err?.code))return res.status(503).json({error:'Database is unavailable. Start PostgreSQL and verify DATABASE_URL.'});res.status(500).json({error:'Internal server error'})});
httpServer.listen(Number(process.env.PORT)||4000,()=>console.log('Encore API listening'));
